version: '3.3'
services:
        iri:
                container_name: iota_iri
                image: iotaledger/iri:latest
                ports:
                        # Local API Port
                        - "127.0.0.1:14266:14266"                           # <1>
                        # Remote API Port
                        - "14265:14265"                                     # <2>
                        - "14600:14600/udp"                                 # <3>
                        - "15600:15600/tcp"                                 # <4>
                volumes:
                        - ./iri.ini:/iri/conf/iri.ini:ro                    # <5>
                        - ./data:/iri/data:rw                               # <6>
                environment:
                        - JAVA_MAX_MEMORY=8192m                             # <7>
                        - JAVA_MIN_MEMORY=256m                              # <8>
                        - DOCKER_IRI_MONITORING_API_PORT_ENABLE=1           # <9>
                restart: unless-stopped
                command: ["-c", "/iri/conf/iri.ini"]
                network_mode: "host"