version: '3.3'
services:
        iri:
                container_name: iota_iri
                image: iotaledger/iri:latest
                ports:
                        # Local API Port
                        - "127.0.0.1:14266:14266"
                        # Remote API Port
                        - "14265:14265"
                        - "14600:14600/udp"
                        - "15600:15600/tcp"
                volumes:
                        - ./iri.ini:/iri/conf/iri.ini:ro
                        - ./data:/iri/data:rw
                environment:
                        - JAVA_MAX_MEMORY=8192m
                        - JAVA_MIN_MEMORY=256m
                        - DOCKER_IRI_MONITORING_API_PORT_ENABLE=1
                restart: unless-stopped
                command: ["-c", "/iri/conf/iri.ini"]
                network_mode: "host"