:toc:
:toc-placement!:

= Simple IOTA IRI Setup with Docker

This is my simple setup of IOTA IRI (IOTA Reference Implementation) with Docker.

There are already some good tutorials and complete setups, such as https://github.com/nuriel77/iri-playbook[IRI Playbook] and https://iota.partners[IOTA Partners]. However, they do much more than just provide an IOTA IRI, so here is my simple and minimalist setup.

I'm using Debian 10 (Buster), so this setup is designed for it, but with a few adjustments it should run on other systems as well.

toc::[]

== Requirements

* Server with a static IP Address
* 4 GB RAM (preferable 8GB)
* 2 cores (preferable 4 cores)
* Some Disk Space (preferable SSD)


I'm using a VPS (virtual private server) from https://contabo.com/?show=vps[Contabo], called 'VPS L SSD'.

== Docker Installation

First we need to install Docker and Docker-Compose.
These steps are well documented on the official docker website, so I will just link to them.

https://docs.docker.com/install/linux/docker-ce/debian/[Docker]

https://docs.docker.com/compose/install/[Docker-Compose]

== Setup
Create folder structure (you can customize the location if you want) and download the two required files:
[source,bash]
----
mkdir -p /root/docker/iota_iri
cd /root/docker/iota_iri
wget https://raw.githubusercontent.com/oyren/yet_another_iota_iri_setup/master/docker-compose.yml
wget https://raw.githubusercontent.com/oyren/yet_another_iota_iri_setup/master/iri.ini
----


.docker-compose.yml
[source,yml]
----
version: '3.3'
services:
        iri:
                container_name: iota_iri
                image: iotaledger/iri:latest
                ports:
                        # Local API Port
                        - "127.0.0.1:14266:14266"                           # <1>
                        # Remote API Port
                        - "14265:14265"                                     # <2>
                        - "14600:14600/udp"                                 # <3>
                        - "15600:15600/tcp"                                 # <4>
                volumes:
                        - ./iri.ini:/iri/conf/iri.ini:ro                    # <5>
                        - ./data:/iri/data:rw                               # <6>
                environment:
                        - JAVA_MAX_MEMORY=8192m                             # <7>
                        - JAVA_MIN_MEMORY=256m                              # <8>
                        - DOCKER_IRI_MONITORING_API_PORT_ENABLE=1           # <9>
                restart: unless-stopped
                command: ["-c", "/iri/conf/iri.ini"]
                network_mode: "host"
----
<1> Bind host port 14266 to Docker port 14266 for local API commands: like listing neighbors
<2> Bind host port 14265 to Docker port 14265 for remote API commands
<3> Bind host port 14600 to Docker port 14600 as UDP receiver port
<4> Bind host port 15600 to Docker port 15600 as TCP receiver port
<5> Forward iri.ini with read access
<6> Mount data folder to save the database and logs
<7> IMPORTANT: You should change this! Here is the maximum amount of memory defined JAVA could use.
<8> Java min memory
<9> Enables local API port 14266

If you can't use one of this ports, you can change the host Port (left side) then.

.iri.ini
[source,ini]
----
[IRI]
PORT = 14265                    # <1>
UDP_RECEIVER_PORT = 14600       # <2>
TCP_RECEIVER_PORT = 15600       # <3>
HEADLESS = true
DEBUG = false
TESTNET = false

REMOTE_LIMIT_API = "removeNeighbors, addNeighbors, getNeighbors, setApiRateLimit"
LOCAL_SNAPSHOTS_ENABLED = false

NEIGHBORS = udp://first.neighbor.com:14600 udp://second.neighbor.com:14600  # <4>
----
<1> Remote API port
<2> UDP receiver port
<3> TCP receiver port
<4> IMPORTANT: Add neighbors here. You can find some in the https://discord.gg/PshQfX3[IOTA Discord] under `#nodesharing`


== Usage
.Start the Docker Container/IRI
[source,bash]
----
docker-compose -f /root/docker/iota_iri/docker-compose.yml up -d
----

.Stop the Docker Container/IRI
[source,bash]
----
docker-compose -f /root/docker/iota_iri/docker-compose.yml down
----

.Restart the Docker Container/IRI
[source,bash]
----
docker-compose -f /root/docker/iota_iri/docker-compose.yml restart
----


=== Update
.Start the Docker Container/IRI
[source,bash]
----
docker-compose -f /root/docker/iota_iri/docker-compose.yml down
docker-compose -f /root/docker/iota_iri/docker-compose.yml up -d
----

=== Troubleshooting/Debugging
[source,bash]
----
docker logs -f iota_iri
----
